@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
hide empty members
class C0 as ":CircularEconomyNetwork\nname = GreenLoop\n" {
}
class C1 as ":Component\nidentifier = C-301\nname = Motor\nrecycled = false\nlifecycleState = ASSEMBLED\n" {
}
class C2 as ":Component\nidentifier = C-300\nname = Gearbox\nrecycled = true\nlifecycleState = IN_LOOP\n" {
}
class C3 as ":Customer\nname = Bob\nloyaltyTier = BASIC\n" {
}
class C4 as ":Customer\nname = Alice\nloyaltyTier = PREMIUM\n" {
}
class C5 as ":DistributionPartner\nname = RetailerOne\nomniChannel = false\n" {
}
class C6 as ":Facility\nname = RepairHubA\noperationalSince = 10-12-1999\n" {
}
class C7 as ":Facility\nname = RecycleCenter1\noperationalSince = 10-12-1999\n" {
}
class C8 as ":Facility\nname = RefurbWien\noperationalSince = 10-12-1999\n" {
}
class C9 as ":FacilityProfile\ncategory = REPAIR\nwaterSaved = 845.0\nenergySaved = 65.0\nco2Emissions = 35.0\n" {
}
class C10 as ":FacilityProfile\ncategory = REPAIR\nwaterSaved = 845.0\nenergySaved = 65.0\nco2Emissions = 35.0\n" {
}
class C11 as ":FacilityProfile\ncategory = REPAIR\nwaterSaved = 845.0\nenergySaved = 65.0\nco2Emissions = 35.0\n" {
}
class C12 as ":Producer\nname = AcmeCorp\nproductionCapacity = 0.0\n" {
}
class C13 as ":Product\nid = P-300\nname = Gadget\nbasePrice = 149.99\nassemblyDate = Wed Nov 20 00:00:00 CET 2024\n" {
}
class C14 as ":Purchase\nid = Alice-O1\ndate = Sun Nov 30 00:00:00 CET 2025\n" {
}
class C15 as ":PurchaseEvent\neventId = 2\ndate = Sun Nov 30 00:00:00 CET 2025\ndelivered = false\ndeliveryDate = Sun Nov 30 00:00:00 CET 2025\n" {
}
class C16 as ":RecycleProcess\nenergySavedKWh = 65.0\nwaterSavedL = 845.0\n" {
}
class C17 as ":RefurbishProcess\nenergySavedKWh = 65.0\nwaterSavedL = 845.0\n" {
}
class C18 as ":RepairProcess\nenergySavedKWh = 65.0\nwaterSavedL = 845.0\n" {
}
class C19 as ":ReturnEvent\neventId = 3\nreason = Bad Quality\ntype = REPAIR\n" {
}
class C20 as ":ReturnOrder\nid = Alice-R1\ndate = Sat Dec 06 00:00:00 CET 2025\nreason = Bad Quality\n" {
}
class C21 as ":ShipmentEvent\neventId = 6\ndate = Sat Dec 06 00:00:00 CET 2025\ndelivered = false\ndeliveryDate = Sat Dec 06 00:00:00 CET 2025\nname = A-R0-REP\nshipmentType = AIR\nco2Emissions = 20.0\n" {
}
class C22 as ":ShipmentEvent\neventId = 5\ndate = Sat Dec 06 00:00:00 CET 2025\ndelivered = false\ndeliveryDate = Sat Dec 06 00:00:00 CET 2025\nname = A-R0-REF\nshipmentType = AIR\nco2Emissions = 20.0\n" {
}
class C23 as ":ShipmentEvent\neventId = 4\ndate = Sat Dec 06 00:00:00 CET 2025\ndelivered = false\ndeliveryDate = Sat Dec 06 00:00:00 CET 2025\nname = A-R0-REC\nshipmentType = AIR\nco2Emissions = 20.0\n" {
}
class C24 as ":SustainabilityMetric\nname = ReduceWaste\ndescription = Minimise waste in process\nthreshold = 10.0\ncomparator = MIN\nunit = ppm\n" {
}
class C25 as ":SustainabilityMetric\nname = ImproveReuse\ndescription = Increase reuse rate\nthreshold = 20.0\ncomparator = MAX\nunit = wpm\n" {
}
C0 --> C12 : actors
C12 --> C2 : components
C12 --> C1 : components
C0 --> C5 : actors
C0 --> C4 : actors
C4 --> C14 : orders
C14 --> C15 : event
C4 --> C20 : returns
C20 --> C19 : event
C20 --> C16 : circularProcesses
C16 --> C23 : shipmentEvent
C20 --> C17 : circularProcesses
C17 --> C22 : shipmentEvent
C20 --> C18 : circularProcesses
C18 --> C21 : shipmentEvent
C0 --> C3 : actors
C0 --> C24 : metrics
C0 --> C25 : metrics
C0 --> C7 : facilities
C7 --> C9 : profile
C0 --> C8 : facilities
C8 --> C11 : profile
C0 --> C6 : facilities
C6 --> C10 : profile
C0 --> C13 : products
C6 ..> C25 : metrics
C7 ..> C24 : metrics
C7 ..> C25 : metrics
C18 ..> C6 : facility
C20 ..> C14 : order
C16 ..> C7 : facility
C16 ..> C2 : components
C16 ..> C1 : components
C17 ..> C8 : facility
C8 ..> C25 : metrics
C14 ..> C13 : product
C13 ..> C5 : retailer
C13 ..> C2 : parts
C13 ..> C1 : parts
@enduml
